app:
    resource: '@AppBundle/Controller/'
    type: annotation

trello:
    resource: '@TrelloBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
