services:
    app.manager.plugin:
        class: AppBundle\Plugin\PluginManager

    app.generator.use_case:
        class: AppBundle\Generator\UseCase\UseCaseGenerator
        calls:
            - { method: addGenerator, arguments: ['@app.generator.use_case.lithuanian'] }
            - { method: addGenerator, arguments: ['@app.generator.use_case.english'] }

    app.generator.use_case.lithuanian:
        class: AppBundle\Generator\UseCase\LithuanianGenerator
        arguments:
          - '@doctrine.orm.entity_manager'

    app.generator.use_case.english:
        class: AppBundle\Generator\UseCase\EnglishGenerator
        arguments:
          - '@doctrine.orm.entity_manager'

    app.generator.dictionary:
        class: AppBundle\Generator\DictionaryGenerator
        arguments:
          - '@app.client.parts_of_speech'

    app.client.yuml:
        class: AppBundle\Client\yUmlClient

    app.client.parts_of_speech:
        class: AppBundle\Client\PartsOfSpeechClient
