services:
    app.manager.plugin:
        class: AppBundle\Plugin\PluginManager

    app.generator.use_case:
        class: AppBundle\Generator\UseCaseGenerator
        arguments:
          - '@doctrine.orm.entity_manager'

    app.client.yuml:
        class: AppBundle\Client\yUmlClient
