services:
    trello.plugin:
        class: TrelloBundle\Plugin\TrelloPlugin
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@twig'
          - '@router'
        tags:
          - { name: 'app.plugin' }
